version: "3.7"

services:
  db:
    platform: linux/x86_64
    container_name: kotlin_mysql
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asis/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

    volumes:
      - ./mysql_data:/var/lib/mysql